### ISSUE TITLE
Confused by clippy warn(op_ref)

### ISSUE THREAD

**Issue by jgilray** [rust-lang-nursery/rust-clippy#2658] opened 2018-04-11 01:30 UTC
I'm confused by the following clippy warning:
```rust
warning: taken reference of right operand
  --> src/main.rs:55:31
   |
55 |                   .filter(|d| d <= &p) {  // include divisors of p^2 + 1 up to p
   |                               ^^^^^--
   |                                    |
   |                                    help: use the right value directly: `p`
   |
   = note: #[warn(op_ref)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.193/index.html#op_ref
```
please note that the compiler won't let me use "p" in place of "&p".  I followed the help link listed above and didn't understand what it was trying to tell me.

Here is the code where the warning occured:
```rust
    let sieve = Sieve::new(((PLIM * PLIM) as f64).sqrt() as usize);
    let mut v: Vec<usize> = vec![];
    for p in 1..PLIM {
        for d in Factors::new(&sieve
                  .factor(p*p+1).unwrap()).into_iter()
                  .filter(|d| d <= &p) {  // include divisors of p^2 + 1 up to p
            let r = (p * (p + d) + 1) / d;
            if r < 2_usize.pow(31) {  // ensure that don't exceed std::u64::MAX
                v.push(p * (p + d) * r);
            }
        }                                  
    }
```

**Comment by mikerite** [comment] 2018-04-11 05:52
This is a duplicate of  #2597.
The suggestion isn't clear. The lint wants you to deref the `d` instead of of referencing `p`.
https://rust-lang-nursery.github.io/rust-clippy/v0.0.193/index.html#op_ref

**Closed** 2018-04-11 05:53 UTC
