### ISSUE TITLE
redundant_clone has no docs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#3434] opened 2018-11-16 16:41 UTC
`clippy 0.0.212 (f5d868c 2018-11-15)`

https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#redundant_clone does not show anything.

**Comment by mati865** [comment] 2018-11-16 17:12
Basically the same thing as https://github.com/rust-lang-nursery/rust-clippy/issues/3409
`v0.0.212` directory is 4 months old now, [`master` works fine](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#redundant_clone).

**Comment by oli-obk** [comment] 2018-11-20 15:21
Closing as duplicate of #3409

**Closed by oli-obk** 2018-11-20 15:21 UTC
Labels: L-documentation, L-website
