### ISSUE TITLE
build scripts not linted

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#2912] opened 2018-07-11 12:39 UTC
When the project uses ````build.rs```` build script, ````cargo build```` will show normal warnings on the build scripts, if there are any, however ````cargo clippy```` will not lint the build script.

**Comment by phansch** [comment] 2018-07-11 15:23
Thanks for the report, I think this is a duplicate of https://github.com/rust-lang-nursery/rust-clippy/issues/2802, so I'm going ahead and close this

**Closed by phansch** 2018-07-11 15:23 UTC
