### ISSUE TITLE
let_unit_value giving suggestion that fails to compile if implemented

### ISSUE THREAD

**Issue by mhlakhani** [rust-lang-nursery/rust-clippy#2331] opened 2018-01-06 01:34 UTC
In 1.23, [FromIterator<()> for () was stabilized.](https://github.com/rust-lang/rust/pull/45379) I tried to write some new code to use this feature. As a simplified example I have the code in this playground:

https://play.rust-lang.org/?gist=3d3f6bde3183c079b072006ecf26b389&version=stable

Clippy will report the error on line 5. However if I remove the annotation and change it to this: 

https://play.rust-lang.org/?gist=286a63d7f9e930265093ad211b5ddfc1&version=stable

I now get a compile error because the compiler doesn't know the return type.

Should clippy not warn in this case?

PS: This seemed different enough from https://github.com/rust-lang-nursery/rust-clippy/issues/1502 that I filed a separate issue, feel free to merge.

**Comment by oli-obk** [comment] 2018-01-08 10:01
Yea this is a dupe of #1502

commenting further there

**Closed by oli-obk** 2018-01-08 10:01 UTC
