### ISSUE TITLE
Could not obtain cargo metadata when using --manifest-path

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2525] opened 2018-03-13 17:12 UTC
```bash
cargo new repro
cargo clippy --manifest-path repro/Cargo.toml
```

The output is:

```
     Created library `repro` project
error: Could not obtain cargo metadata.
```

This looks a lot like #973 and #1023 and #1611 except less panicky.

It does work if you use `--manifest-path=repro/Cargo.toml` with `=`-sign instead of space.

**Comment by oli-obk** [comment] 2018-03-14 09:35
Whoops. This was due to updates to the cargo metadata crate.

**Comment by phansch** [comment] 2018-03-30 11:50
Looks like this is fixed in the latest version. I don't get any errors when I try to reproduce it, so I'm going ahead and close this.

@dtolnay Feel free to re-open if you still get this error with 0.0.191 :heart:

**Closed by phansch** 2018-03-30 11:50 UTC
Labels: L-bug :beetle:, good first issue
