### ISSUE TITLE
ICE in markup5ever

### ISSUE THREAD

**Issue by o01eg** [rust-lang-nursery/rust-clippy#3111] opened 2018-09-02 05:49 UTC
When I trying to check project I got ICE on `markup5ever` dependency:

```
    Checking markup5ever v0.7.2
     Running `/usr/bin/clippy-driver rustc --crate-name markup5ever /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/markup5ever-0.7.2/lib.rs --crate-type lib --emit=dep-info,metadata -C opt-level=3 -C metadata=00aaa33cba495085 -C extra-filename=-00aaa33cba495085 --out-dir /mnt/another/srcs/GIT/tokio-xmpp/target/release/deps -L dependency=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps --extern phf=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps/libphf-a154f63fe3738034.rmeta --extern string_cache=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps/libstring_cache-490acbbbeea996d7.rmeta --extern tendril=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps/libtendril-950d7fa0d679bbd1.rmeta --cap-lints allow -L /usr/lib/rust-9999/ -L /usr/lib64/rust-9999/rustlib/x86_64-unknown-linux-gnu/lib/`
thread 'main' panicked at 'visit_mac disabled by default', libsyntax/visit.rs:112:9
stack backtrace:
   0: rust_metadata_std_78458fdf0b87d134b02701181473df62
   1: rust_metadata_std_78458fdf0b87d134b02701181473df62
   2: rust_metadata_std_78458fdf0b87d134b02701181473df62
   3: rust_metadata_std_78458fdf0b87d134b02701181473df62
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item
  13: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod
  14: rust_metadata_rustc_61b5b810c573e5ac5c4db3d2fde9a4f1
  15: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item
  16: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod
  17: rust_metadata_rustc_61b5b810c573e5ac5c4db3d2fde9a4f1
  18: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item
  19: <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod
  20: rustc::lint::context::check_ast_crate
  21: <unknown>
  22: <unknown>
  23: rustc_driver::driver::compile_input
  24: <unknown>
  25: <unknown>
  26: rustc_driver::run_compiler
  27: <unknown>
  28: <unknown>
  29: __rust_maybe_catch_panic
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: rust_metadata_std_78458fdf0b87d134b02701181473df62
  34: __rust_maybe_catch_panic
  35: std::rt::lang_start_internal
  36: <unknown>
  37: __libc_start_main
  38: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-dev (1114ab684 2018-08-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `markup5ever`.

Caused by:
  process didn't exit successfully: `/usr/bin/clippy-driver rustc --crate-name markup5ever /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/markup5ever-0.7.2/lib.rs --crate-type lib --emit=dep-info,metadata -C opt-level=3 -C metadata=00aaa33cba495085 -C extra-filename=-00aaa33cba495085 --out-dir /mnt/another/srcs/GIT/tokio-xmpp/target/release/deps -L dependency=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps --extern phf=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps/libphf-a154f63fe3738034.rmeta --extern string_cache=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps/libstring_cache-490acbbbeea996d7.rmeta --extern tendril=/mnt/another/srcs/GIT/tokio-xmpp/target/release/deps/libtendril-950d7fa0d679bbd1.rmeta --cap-lints allow -L /usr/lib/rust-9999/ -L /usr/lib64/rust-9999/rustlib/x86_64-unknown-linux-gnu/lib/` (exit code: 101)
```

Versions: 
```
$ rustc --version --verbose
rustc 1.30.0-dev (1114ab684 2018-08-31)
binary: rustc
commit-hash: 1114ab684fbad001c4e580326d8eb4d8c4e917d3
commit-date: 2018-08-31
host: x86_64-unknown-linux-gnu
release: 1.30.0-dev
LLVM version: 7.0
$ cargo clippy --version --verbose
0.0.212
```

Clippy version is shipped with rust.

**Comment by Manishearth** [comment] 2018-09-02 05:54
Dupe of https://github.com/rust-lang-nursery/rust-clippy/issues/3078

you may need to wait for the next nightly.

**Closed** 2018-09-02 05:57 UTC
