### ISSUE TITLE
cargo clippy doesn't run from a subfolder

### ISSUE THREAD

**Issue by dzamlo** [rust-lang-nursery/rust-clippy#1325] opened 2016-11-07 23:01 UTC
When running cargo clippy from the `src` or `examples` folder, I get the following error
```
RUST_BACKTRACE=1 cargo clippy
thread 'main' panicked at 'could not find matching package', ../src/libcore/option.rs:705
stack backtrace:
   1:     0x7f05e3ab27fa - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f05e3ac499f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x7f05e3ac1256 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x7f05e3ac1907 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x7f05e3ac1794 - std::panicking::begin_panic::ha6a0d553db9869ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x7f05e3ac16b9 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x7f05e3ac1647 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x7f05e3b1284d - core::panicking::panic_fmt::he441b2ea2036b98a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x7f05e3b128bd - core::option::expect_failed::h7136772e5b75d3f8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:705
  10:     0x563bc81587d1 - <core::option::Option<T>>::expect::h29fe390f41d2a374
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:293
  11:     0x563bc81919b7 - cargo_clippy::main::hcd30f9d87e2c270a
                        at /home/loic/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.97/src/main.rs:187
  12:     0x7f05e3acc8aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  13:     0x7f05e3ac27f5 - std::rt::lang_start::h74b3afbdd8daef1c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  14:     0x563bc8195d33 - main
  15:     0x7f05e2f88290 - __libc_start_main
  16:     0x563bc814ab99 - _start
  17:                0x0 - <unknown>
```

I'm running the latest nightly and installed clippy with `cargo install --force --debug clippy`. There is the same issue without the `--debug`.

**Comment by oli-obk** [comment] 2016-11-08 06:57
This is a known limitation right now( #909). Not sure yet what causes it

**Comment by jplatte** [comment] 2017-05-18 19:36
@ogham This is not a duplicate of #909. That issue is about `cargo build` not working in a subdirectory when you have a `clippy.toml`. This one is about `cargo clippy` not working from a subdirectory, no matter if you have a `clippy.toml` or not.

**Comment by ogham** [comment] 2017-05-19 15:52
@jplatte Did you mean to mention oli-obk?

**Comment by jplatte** [comment] 2017-05-19 17:07
Uhhh, yeah, seems like GitHub's username autocompletion fooled me, sorry ^^°

@oli-obk, can you reopen (or explain how this is a dupe of #909)?

**Comment by oli-obk** [comment] 2017-05-19 19:40
Sorry about that. I thought we already had an issue open and didn't look too closely

**Comment by Arnavion** [comment] 2017-08-01 02:18
This is fixed now. #1860 + #1896

**Comment by oli-obk** [comment] 2017-08-01 05:43
🎉

**Closed by oli-obk** 2017-08-01 05:43 UTC
