### ISSUE TITLE
False positive fn_to_numeric_cast_with_truncation:casting function pointer `some_fn` to `*mut libc::c_void`, which truncates the value

### ISSUE THREAD

**Issue by sdroege** [rust-lang-nursery/rust-clippy#3296] opened 2018-10-11 08:34 UTC
clippy 0.0.212 (32b1d1f 2018-10-05)

Casting a raw function pointer to some other pointer shouldn't involve any truncation, so this seems to be a false positive. It suggests using `usize` instead of `*mut c_void`, but both have the same size.

**Comment by phansch** [comment] 2018-10-12 05:55
This is looks like a duplicate of https://github.com/rust-lang-nursery/rust-clippy/issues/3275 and should be fixed in the next version available via rustup.

Don't hestitate to re-open if it's still broken with the next nightly Clippy.

**Closed by phansch** 2018-10-12 05:55 UTC
