### ISSUE TITLE
Clippy crashes when packed_struct is used

### ISSUE THREAD

**Issue by samueltardieu** [rust-lang-nursery/rust-clippy#2431] opened 2018-02-02 11:23 UTC
The code below compiles and runs fine, but crashes `cargo clippy`. This is a reduced reproducer.

```bash
% cargo clippy --version
0.0.184
```

```bash
% cargo clippy
bin: t
   Compiling t v0.1.0 (file:///tmp/t)
warning: unnecessary parentheses around assigned value
 --> src/main.rs:6:10
  |
6 | #[derive(PackedStruct)]
  |          ^^^^^^^^^^^^ help: remove these parentheses
  |
  = note: #[warn(unused_parens)] on by default

warning: unnecessary parentheses around assigned value
 --> src/main.rs:6:10
  |
6 | #[derive(PackedStruct)]
  |          ^^^^^^^^^^^^ help: remove these parentheses

warning: the loop variable `i` is used to index `packed`
 --> src/main.rs:6:10
  |
6 | #[derive(PackedStruct)]
  |          ^^^^^^^^^^^^
  |
  = note: #[warn(needless_range_loop)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.184/index.html#needless_range_loop
thread 'rustc' panicked at 'begin <= end (21 <= 9) when slicing `#[derive(PackedStruct)]`', libcore/str/mod.rs:2225:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (def3269a7 2018-01-30) running on x86_64-unknown-linux-gnu

error: Could not compile `t`.

To learn more, run the command again with --verbose.
```

```bash
% cat src/main.rs
extern crate packed_struct;
#[macro_use] extern crate packed_struct_codegen;

use packed_struct::prelude::*;

#[derive(PackedStruct)]
#[packed_struct(bit_numbering = "msb0")]
pub struct LEDDriverConfig {
    #[packed_field(bits = "7..15", endian = "msb")]
    ccr: Integer<u16, ::packed_bits::Bits9>,
    #[packed_field(bits = "4..6")]
    bc: Integer<u8, ::packed_bits::Bits3>,
    #[packed_field(bits = "3")]
    poker_trans_mode: Integer<u8, ::packed_bits::Bits1>,
    #[packed_field(bits = "0..2")]
    lgse2: Integer<u8, ::packed_bits::Bits3>,
}

fn main() {
}
```

```bash
% cat Cargo.toml 
[package]                  
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "t"
version = "0.1.0"

[dependencies]
packed_struct = "0.1.0"
packed_struct_codegen = "0.1.0"
```

The backtrace is

```
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::str::slice_error_fail
             at libcore/str/mod.rs:0
  10: rustc_errors::CodeSuggestion::splice_lines::push_trailing
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit
  14: rustc_errors::Handler::emit_db
  15: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  16: clippy_lints::utils::span_lint_and_then
  17: clippy_lints::loops::check_for_loop
  18: <clippy_lints::loops::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  20: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_local
  21: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  23: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  25: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  27: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  28: rustc::hir::intravisit::walk_impl_item
  29: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  30: rustc::hir::intravisit::walk_impl_item_ref
  31: rustc::hir::intravisit::walk_item
  32: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  33: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  34: rustc::hir::intravisit::walk_crate
  35: rustc::lint::context::check_crate
  36: <std::thread::local::LocalKey<T>>::with
  37: <std::thread::local::LocalKey<T>>::with
  38: rustc::ty::context::TyCtxt::create_and_enter
  39: rustc_driver::driver::compile_input
  40: rustc_driver::run_compiler
```

**Comment by phansch** [comment] 2018-10-27 08:51
I can't reproduce this anymore. I believe this was fixed by https://github.com/rust-lang-nursery/rust-clippy/pull/3330. The backtrace also points at loop lints.

I'm going ahead and close this. Feel free to re-open if this still happens.

**Closed by phansch** 2018-10-27 08:51 UTC
Labels: L-crash :boom:, T-macros

**Comment by samueltardieu** [comment] 2018-10-27 08:56
Indeed, confirmed working.
