### ISSUE TITLE
Detect broken crate attributes

### ISSUE THREAD

**Issue by nox** [rust-lang-nursery/rust-clippy#1165] opened 2016-08-16 13:41 UTC
I want to avoid this embarrassing commit next time: https://github.com/nox/hyper_serde/commit/b1f2eac001d286e9209706fc2e48480543b57fe4

**Comment by oli-obk** [comment] 2016-08-16 13:46
I just made the exact same mistake 2 hours ago...

**Comment by oli-obk** [comment] 2016-08-17 10:24
So... that one would have been caught. But it would be nice if we'd detect empty lines between a `#[allow(foo)]` attribute and the next item. So I'm leaving this open

**Comment by mcarton** [comment] 2016-08-17 14:50
Dupe of #770.

**Comment by phansch** [comment] 2018-01-06 11:33
This seems straightforward for a first lint, so I'll work on detecting newlines after attributes in the next couple of days 👍

**Comment by phansch** [comment] 2018-01-06 12:29
Hmm, as I learned in #1378 that clippy only works on the AST which doesn't include empty lines obviously. This seems a bit more difficult now, and maybe something for rustfmt instead? Or is there some other way to look for empty lines @oli-obk?

**Comment by oli-obk** [comment] 2018-01-08 10:05
@phansch you can create a span from the attribute to the following item, then use the `snippet_opt` function to get the text and check whether there are empty newlines in that text

**Closed** 2018-01-30 12:09 UTC
Labels: A-correctness, L-enhancement, good first issue, hacktoberfest
